name: .Build intellect.kpi.ua project


inputs:
  project: intellect-kpi-ua
  tag:  $(date +%s)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Build with dotnet
      run: dotnet build --configuration Release      

    - name: Publish Web App
      run: dotnet publish ./src/Site/Site.csproj --configuration Release -o ./docker/out    
      
    - name: Build the Docker image (release tag)
      run: docker build ./docker --file ./docker/Dockerfile --tag ${{ inputs.project }}:${{ inputs.tag }}

    - name: Build the Docker image (latest tag)
      run: docker build ./docker --file ./docker/Dockerfile --tag ${{ inputs.project }}:latest
    
    - name: Docker Auth
      run: docker login -u ${{ secrets.GH_USERNAME }} -p ${{ secrets.GH_TOKEN }} docker.pkg.github.com

    - name: Push the Docker image (release tag)
      run: docker push docker.pkg.github.com/kpi-ua/devdigest.today/${{ inputs.project }}:${{ inputs.tag }}

    - name: Push the Docker image (latest tag)
      run: docker push docker.pkg.github.com/kpi-ua/devdigest.today/${{ inputs.project }}:latest
      
    