name: .Build intellect.kpi.ua project

env:
  project: 'intellect-kpi-ua'
  tag: ${{ github.sha }}
  tag-latest: 'latest'
  docker-registry-url: 'docker.pkg.github.com/kpi-ua/intellect.kpi.ua/'

on: [push]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Build and publish Web App
      run: |
        dotnet build --configuration Release
        dotnet publish ./src/Site/Site.csproj --configuration Release -o ./docker/out
      
    - name: Build Docker images
      run: |
        docker build ./docker --file ./docker/Dockerfile --tag ${{ env.project }}:${{ env.tag }}
        docker build ./docker --file ./docker/Dockerfile --tag ${{ env.project }}:${{ env.tag-latest }}
    
    - name: Docker Auth
      run: docker login -u ${{ secrets.GH_USERNAME }} -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com

    - name: Push Docker images
      run: |
        docker tag ${{ env.project }}:${{ env.tag }} ${{ env.docker-registry-url }}${{ env.project }}:${{ env.tag }}
        docker tag ${{ env.project }}:${{ env.tag-latest }} ${{ env.docker-registry-url }}${{ env.project }}:${{ env.tag-latest }}
        docker push ${{ env.docker-registry-url }}${{ env.project }}:${{ env.tag }}
        docker push ${{ env.docker-registry-url }}${{ env.project }}:${{ env.tag-latest }}
      
    
