name: .Build intellect.kpi.ua project

env:
  project: 'intellect-kpi-ua'
  tag: ${{ github.sha }}

on: [push]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Build with dotnet
      run: dotnet build --configuration Release      

    - name: Publish Web App
      run: dotnet publish ./src/Site/Site.csproj --configuration Release -o ./docker/out    
      
    - name: Build the Docker image (release tag)
      run: docker build ./docker --file ./docker/Dockerfile --tag ${{ env.project }}:${{ env.tag }}

    - name: Build the Docker image (latest tag)
      run: docker build ./docker --file ./docker/Dockerfile --tag ${{ env.project }}:latest
    
    - name: Docker Auth
      run: docker login -u ${{ secrets.GH_USERNAME }} -p ${{ secrets.GH_TOKEN }} docker.pkg.github.com

    - name: Push the Docker image (release tag)
      run: docker push docker.pkg.github.com/kpi-ua/intellect.kpi.ua/${{ env.project }}:${{ env.tag }}

    - name: Push the Docker image (latest tag)
      run: docker push docker.pkg.github.com/kpi-ua/intellect.kpi.ua/${{ env.project }}:latest
      
    
